
// ! ESSAS CONEXOES DEVEM SER ALTERADAS NÃO PARA SEQUENCIA 1 2 3, POIS ISSO NA PLACA ISSO DISTRIBUIRÁ MAL OS JUMPPERS
// ! CRIAR UMA LOGICA DIAGONAL OU SO IMPAS OU SÓ PARESS

/*
? GPIO_LEDS 
* LED0 P8.3 GPIO1_6
* LED1 P8.5 GPIO1_7
* LED2 P8.7 GPIO1_2
* LED3 P8.9 GPIO1_3
* LED4 P8.11 GPIO2_2
*/


int main(){




   return 0;
}